**Contexte :** préparer et analyser des données de capteurs multi-bâtiments avant leur transmission à un futur système de Machine Learning de détection d'anomalies.

In [1]:
import pandas as pd
import numpy as np

# Partie 1 : Series

Une **Series** est un tableau 1D étiqueté (un index + des valeurs) : la brique de base de Pandas, équivalente à une colonne de tableau.

In [24]:
# 1) Series de 4 températures
temperatures=pd.Series([24.5, 25.1, 26.3, 27.0])
print(f"1) {temperatures}")

# 2) Index
print(f"2) L'Index: {temperatures.index}\n")

# 3) Première valeur
print(f"3) Première Valeure: {temperatures.iloc[0]}\n")

# 4) Dernière valeur
print(f"4) Dernière valeur: {temperatures.iloc[-1]}\n")

1) 0    24.5
1    25.1
2    26.3
3    27.0
dtype: float64
2) L'Index: RangeIndex(start=0, stop=4, step=1)

3) Première Valeure: 24.5

4) Dernière valeur: 27.0

In [25]:
# 5) Series indexée par heure (12h, 13h, 14h, 15h)

# Méthode A:
temp_heures_A=pd.Series([24.5, 25.1, 26.3, 27.0],
                       index=["12h", "13h", "14h", "15h"])

temp_heures_B=pd.Series([24.5, 25.1, 26.3, 27.0])
temp_heures_B.index=["12h", "13h", "14h", "15h"]

print(f"5) Méthode A \n {temp_heures_A}\n")
print(f"5) Méthode B \n {temp_heures_B}")

5) Méthode A
 12h    24.5
13h    25.1
14h    26.3
15h    27.0
dtype: float64

5) Méthode B
 12h    24.5
13h    25.1
14h    26.3
15h    27.0
dtype: float64

In [27]:
# 6) Première et dernière valeur

print("Première valeur (12h) :", temp_heures_A.iloc[0])
print("Dernière valeur (15h) :", temp_heures_B.iloc[-1])

Première valeur (12h) : 24.5
Dernière valeur (15h) : 27.0

# Partie 2 : DataFrame

Un **DataFrame** est un tableau 2D étiqueté (lignes + colonnes) : l'équivalent Pandas d'une feuille de tableur ou d'une table SQL.

In [28]:
# 1) DataFrame de test à partir d'un dictionnaire
data={
    "capteur": ["C001", "C002", "C003"],
    "temperature": [24.5, 25.1, 26.3],
    "humidite": [65, 67, 70]
}

df_test=pd.DataFrame(data)
df_test

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

In [29]:
# 2) Import du dataset réel
df=pd.read_csv("../data/mesures_capteurs.csv")

# 3) Dimensions de df
print("Dimension (lignes, colonnes): ", df.shape)

Dimension (lignes, colonnes):  (605, 9)

# Partie 3 : Exploration

Avant toute analyse, on inspecte la structure et le contenu global du DataFrame.

In [30]:
# 1) Premières lignes
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

In [31]:
# 2) 10 Première lignes
df.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK

In [32]:
# 3) Dernières lignes
df.tail()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

In [33]:
# 4) Nombre de lignes
print("Nombre de lignes :", df.shape[0])

# 5) Nombre de colonnes
print("Nombre de colonnes :", df.shape[1])

# 6) Noms des colonnes
print("Colonnes :", df.columns.tolist())

Nombre de lignes : 605
Nombre de colonnes : 9
Colonnes : ['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature', 'humidite', 'pression', 'consommation', 'etat']

In [34]:
# 7) Informations générales (types, valeurs non nulles, mémoire)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    object
 1   date_heure    605 non-null    object
 2   id_capteur    605 non-null    object
 3   batiment      605 non-null    object
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    object
dtypes: float64(4), object(5)
memory usage: 42.7+ KB

In [35]:
# 8) Statistiques descriptives des colonnes numériques 
df.describe()

       temperature   humidite     pression  consommation
count   599.000000  600.00000   600.000000    600.000000
mean     24.878314   64.92620  1012.221900    208.675417
std       4.059576   10.76905    10.599042     72.243567
min     -18.500000   28.52000   850.000000     18.120000
25%      22.570000   58.17250  1006.790000    160.177500
50%      24.860000   65.37500  1012.855000    206.150000
75%      27.275000   71.61500  1017.827500    254.127500
max      58.700000  145.00000  1038.430000    875.000000