**Contexte :** préparer et analyser des données de capteurs multi-bâtiments avant leur transmission à un futur système de Machine Learning de détection d'anomalies.

In [1]:
import pandas as pd
import numpy as np

# Partie 1 : Series

Une **Series** est un tableau 1D étiqueté (un index + des valeurs) : la brique de base de Pandas, équivalente à une colonne de tableau.

In [24]:
# 1) Series de 4 températures
temperatures=pd.Series([24.5, 25.1, 26.3, 27.0])
print(f"1) {temperatures}")

# 2) Index
print(f"2) L'Index: {temperatures.index}\n")

# 3) Première valeur
print(f"3) Première Valeure: {temperatures.iloc[0]}\n")

# 4) Dernière valeur
print(f"4) Dernière valeur: {temperatures.iloc[-1]}\n")

1) 0    24.5
1    25.1
2    26.3
3    27.0
dtype: float64
2) L'Index: RangeIndex(start=0, stop=4, step=1)

3) Première Valeure: 24.5

4) Dernière valeur: 27.0

In [25]:
# 5) Series indexée par heure (12h, 13h, 14h, 15h)

# Méthode A:
temp_heures_A=pd.Series([24.5, 25.1, 26.3, 27.0],
                       index=["12h", "13h", "14h", "15h"])

temp_heures_B=pd.Series([24.5, 25.1, 26.3, 27.0])
temp_heures_B.index=["12h", "13h", "14h", "15h"]

print(f"5) Méthode A \n {temp_heures_A}\n")
print(f"5) Méthode B \n {temp_heures_B}")

5) Méthode A
 12h    24.5
13h    25.1
14h    26.3
15h    27.0
dtype: float64

5) Méthode B
 12h    24.5
13h    25.1
14h    26.3
15h    27.0
dtype: float64

In [27]:
# 6) Première et dernière valeur

print("Première valeur (12h) :", temp_heures_A.iloc[0])
print("Dernière valeur (15h) :", temp_heures_B.iloc[-1])

Première valeur (12h) : 24.5
Dernière valeur (15h) : 27.0

# Partie 2 : DataFrame

Un **DataFrame** est un tableau 2D étiqueté (lignes + colonnes) : l'équivalent Pandas d'une feuille de tableur ou d'une table SQL.

In [28]:
# 1) DataFrame de test à partir d'un dictionnaire
data={
    "capteur": ["C001", "C002", "C003"],
    "temperature": [24.5, 25.1, 26.3],
    "humidite": [65, 67, 70]
}

df_test=pd.DataFrame(data)
df_test

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

In [29]:
# 2) Import du dataset réel
df=pd.read_csv("../data/mesures_capteurs.csv")

# 3) Dimensions de df
print("Dimension (lignes, colonnes): ", df.shape)

Dimension (lignes, colonnes):  (605, 9)

# Partie 3 : Exploration

Avant toute analyse, on inspecte la structure et le contenu global du DataFrame.

In [30]:
# 1) Premières lignes
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

In [31]:
# 2) 10 Première lignes
df.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK

In [32]:
# 3) Dernières lignes
df.tail()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

In [33]:
# 4) Nombre de lignes
print("Nombre de lignes :", df.shape[0])

# 5) Nombre de colonnes
print("Nombre de colonnes :", df.shape[1])

# 6) Noms des colonnes
print("Colonnes :", df.columns.tolist())

Nombre de lignes : 605
Nombre de colonnes : 9
Colonnes : ['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature', 'humidite', 'pression', 'consommation', 'etat']

In [34]:
# 7) Informations générales (types, valeurs non nulles, mémoire)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    object
 1   date_heure    605 non-null    object
 2   id_capteur    605 non-null    object
 3   batiment      605 non-null    object
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    object
dtypes: float64(4), object(5)
memory usage: 42.7+ KB

In [35]:
# 8) Statistiques descriptives des colonnes numériques 
df.describe()

       temperature   humidite     pression  consommation
count   599.000000  600.00000   600.000000    600.000000
mean     24.878314   64.92620  1012.221900    208.675417
std       4.059576   10.76905    10.599042     72.243567
min     -18.500000   28.52000   850.000000     18.120000
25%      22.570000   58.17250  1006.790000    160.177500
50%      24.860000   65.37500  1012.855000    206.150000
75%      27.275000   71.61500  1017.827500    254.127500
max      58.700000  145.00000  1038.430000    875.000000

# Partie 4 : Sélection

Pandas propose plusieurs façons de sélectionner des colonnes ou des lignes : crochets `[]` pour les colonnes, `.loc` (par étiquette) et `.iloc` (par position) pour les lignes.

In [36]:
# 1) Sélection d'une colonne
df["temperature"]

0      25.46
1      24.00
2      25.82
3      28.23
4      20.58
       ...
600    23.67
601    24.34
602    23.73
603    24.83
604    17.02
Name: temperature, Length: 605, dtype: float64

In [39]:
# 2) Sélection de plusieurs colonnes
df[["temperature", "humidite", "pression", "consommation"]]

     temperature  humidite  pression  consommation
0          25.46     58.06   1008.95        287.28
1          24.00     79.73    993.39        116.20
2          25.82     54.47   1010.32        288.50
3          28.23     69.39   1019.62        136.65
4          20.58     53.80   1016.58        182.62
..           ...       ...       ...           ...
600        23.67     60.28   1015.11        282.36
601        24.34     61.42   1019.43        357.43
602        23.73     63.49   1016.46        152.79
603        24.83     79.77   1017.05        170.97
604        17.02     52.04   1001.14         44.99

[605 rows x 4 columns]

In [40]:
# 3) 5 premières lignes avec loc
df.loc[0:4]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

In [41]:
# 4) 5 premières lignes et 4 premières colonnes avec iloc
df.iloc[0:5, 0:4]

  id_mesure           date_heure id_capteur batiment
0     M0413  2026-01-22 04:00:00       C005     B002
1     M0290  2026-01-17 01:00:00       C002     B001
2     M0077  2026-01-08 04:00:00       C005     B002
3     M0079  2026-01-08 06:00:00       C007     B003
4     M0183  2026-01-12 14:00:00       C003     B001

# Partie 5 : Manipulation des colonnes

On peut ajouter, renommer ou supprimer des colonnes — une étape courante de préparation des données (*feature engineering*).

In [42]:
# 1) Ajout de la colonne temperature_fahrenheit
df["temperature_fahrenheit"]=df["temperature"] * 9/5+32

# 2) Catégorisation de la température avec np.where()
df["niveau_temperature"]=np.where(df["temperature"] > 30, "Elevé", "Normale")

df[["temperature", "temperature_fahrenheit", "niveau_temperature"]].head()

   temperature  temperature_fahrenheit niveau_temperature
0        25.46                  77.828            Normale
1        24.00                  75.200            Normale
2        25.82                  78.476            Normale
3        28.23                  82.814            Normale
4        20.58                  69.044            Normale

In [43]:
# 3) Renommage de la colonne humidite
df=df.rename(columns={"humidite":"humidite_relative"})

# 4) Suppression de la colonne temperature_fahrenheit
df=df.drop(columns=["temperature_fahrenheit"])

df.columns.tolist()

['id_mesure',
 'date_heure',
 'id_capteur',
 'batiment',
 'temperature',
 'humidite_relative',
 'pression',
 'consommation',
 'etat',
 'niveau_temperature']

# Partie 6 : Filtrage

Le filtrage permet d'isoler les lignes qui vérifient une ou plusieurs conditions — essentiel pour repérer les situations anormales.

In [44]:
# 1) Températures > 30°C
temp_elevees=df[df["temperature"] > 30 ]
temp_elevees.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK,Elevé
43,M0575,2026-01-28 22:00:00,C011,B004,34.72,57.50,1008.94,266.22,ALERTE,Elevé
47,M0082,2026-01-08 09:00:00,C010,B004,32.46,72.31,1000.42,276.99,ALERTE,Elevé
63,M0064,2026-01-07 15:00:00,C004,B002,31.19,55.13,1011.04,264.98,OK,Elevé
79,M0275,2026-01-16 10:00:00,C011,B004,31.74,69.95,1020.79,335.89,OK,Elevé

In [45]:
# 2) Température > 30°C ET Humidité > 70
temp_humidite_elevees=df[(df["temperature"] > 30) & (df["humidite_relative"] > 70)]
temp_humidite_elevees.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
47,M0082,2026-01-08 09:00:00,C010,B004,32.46,72.31,1000.42,276.99,ALERTE,Elevé
88,M0288,2026-01-16 23:00:00,C012,B004,30.06,75.30,1014.47,323.32,OK,Elevé
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE,Elevé
145,M0503,2026-01-25 22:00:00,C011,B004,30.57,71.26,1002.88,359.97,OK,Elevé
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE,Elevé

# Partie 7 : Tri

Trier un DataFrame permet de faire ressortir les valeurs extrêmes (pics, records) selon une ou plusieurs colonnes.

In [46]:
# 1) Tri croissant par température
df_trie1=df.sort_values("temperature")

# 2) Tri décroissant par température
df_trie2=df.sort_values("temperature", ascending=False)

df_trie1.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
487,M0538,2026-01-27 09:00:00,C010,B004,-18.50,66.27,1012.49,312.92,ERREUR,Normale
245,M0127,2026-01-10 06:00:00,C007,B003,14.11,145.00,1032.36,169.57,ERREUR,Normale
258,M0223,2026-01-14 06:00:00,C007,B003,15.49,47.96,1006.34,124.90,OK,Normale
249,M0175,2026-01-12 06:00:00,C007,B003,16.04,55.36,1005.68,140.95,OK,Normale
59,M0146,2026-01-11 01:00:00,C002,B001,16.77,53.44,1010.65,131.75,OK,Normale

In [47]:
# 3) Top 10 des températures les plus élevées
top10=df.sort_values("temperature", ascending=False).head(10)
top10

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
502,M0048,2026-01-06 23:00:00,C012,B004,58.70,81.51,1026.79,271.92,ERREUR,Elevé
43,M0575,2026-01-28 22:00:00,C011,B004,34.72,57.50,1008.94,266.22,ALERTE,Elevé
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE,Elevé
211,M0370,2026-01-20 09:00:00,C010,B004,33.29,50.43,1009.87,356.76,ALERTE,Elevé
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE,Elevé
118,M0365,2026-01-20 04:00:00,C005,B002,32.90,65.91,1027.28,246.08,ALERTE,Elevé
520,M0063,2026-01-07 14:00:00,C003,B001,32.72,53.28,1010.05,195.37,ALERTE,Elevé
438,M0558,2026-01-28 05:00:00,C006,B002,32.56,67.77,1016.88,181.51,ALERTE,Elevé
47,M0082,2026-01-08 09:00:00,C010,B004,32.46,72.31,1000.42,276.99,ALERTE,Elevé
169,M0546,2026-01-27 17:00:00,C006,B002,32.36,67.34,998.10,184.89,ALERTE,Elevé

In [48]:
# 4) Tri par bâtiment (croissant) puis température (décroissant)
df_trie_multi=df.sort_values(["batiment", "temperature"], ascending=[True, False])
df_trie_multi.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
520,M0063,2026-01-07 14:00:00,C003,B001,32.72,53.28,1010.05,195.37,ALERTE,Elevé
447,M0170,2026-01-12 01:00:00,C002,B001,31.15,69.20,1016.10,172.49,OK,Elevé
224,M0303,2026-01-17 14:00:00,C003,B001,30.84,67.98,1020.09,157.99,OK,Elevé
500,M0062,2026-01-07 13:00:00,C002,B001,30.39,52.13,1004.23,262.66,OK,Elevé
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK,Normale
467,M0241,2026-01-15 00:00:00,C001,B001,28.85,66.31,1004.98,175.06,OK,Normale
567,M0591,2026-01-29 14:00:00,C003,B001,28.71,55.02,1010.18,201.62,OK,Normale
85,M0074,2026-01-08 01:00:00,C002,B001,28.41,39.33,1011.11,187.94,OK,Normale
293,M0230,2026-01-14 13:00:00,C002,B001,28.31,70.29,1023.91,95.36,OK,Normale
263,M0579,2026-01-29 02:00:00,C003,B001,28.11,65.56,1016.97,196.48,OK,Normale

# Partie 8 : Analyse

Le regroupement (`groupby`) permet de calculer des statistiques par groupe (ici, par bâtiment) — la base de toute analyse comparative.

In [49]:
# 1) ["consommation"].mean()Consommation moyenne par bâtiment
df.groupby("batiment")["consommation"].mean()

batiment
B001    177.870927
B002    221.785333
B003    153.191000
B004    282.552282
Name: consommation, dtype: float64

In [50]:
# 2) Min, Max, Moyenne, Ecart-type de la température par bâtiment
df.groupby("batiment")["temperature"].agg(["min", "max", "mean", "std"])

            min    max       mean       std
batiment
B001      16.77  32.72  23.578824  2.961211
B002      17.67  33.60  25.778000  2.951828
B003      14.11  31.74  23.013699  2.983902
B004     -18.50  58.70  27.119000  5.367361

In [51]:
# 3) Par bâtiment : Max et Moyenne de la température et de la consommation
df.groupby("batiment")[["temperature", "consommation"]].agg(["max", "mean"])

         temperature            consommation
                 max       mean          max        mean
batiment
B001           32.72  23.578824       294.72  177.870927
B002           33.60  25.778000       335.20  221.785333
B003           31.74  23.013699       875.00  153.191000
B004           58.70  27.119000       411.12  282.552282

In [52]:
# 4) Température moyenne globale
print("Température moyenne globale :", round(df["temperature"].mean(), 2))

# 5) Température maximale
print("Température maximale :", df["temperature"].max())

# 6) Consommation totale 
print("Consommation totale :", round(df["consommation"].sum(), 2))

Température moyenne globale : 24.88
Température maximale : 58.7
Consommation totale : 125205.25

In [57]:
# 7) Bâtiment qui consomme le plus en moyenne
conso_moyenne_batiment= df.groupby("batiment")["consommation"].mean()
print("Bâtiment le plus consommateur :", conso_moyenne_batiment.idxmax(),
     "(", round(conso_moyenne_batiment.max(), 2), ")")

Bâtiment le plus consommateur : B004 ( 282.55 )

In [60]:
# 8) Nombre d'alertes par bâtiment
df[df["etat"] == "ALERTE"].groupby("batiment").size()

batiment
B001     2
B002     7
B003     5
B004    15
dtype: int64

# Partie 9 : Gestion des valeurs manquantes

Un modèle de Machine Learning ne peut généralement pas être entraîné sur des données incomplètes : il faut détecter puis traiter les valeurs manquantes (`NaN`).

In [61]:
# 2) Nombre total de valeurs manquantes
print("Total de valeurs manquantes :", df.isna().sum().sum())

Total de valeurs manquantes : 25

In [62]:
# 3) Taux de valeurs manquantes (%)
taux_manquant=df.isna().sum().sum()/df.size*100
print(f"Taux de valeurs manquantes : {taux_manquant: .2f} %")

Taux de valeurs manquantes :  0.41 %

In [63]:
# 4) Lignes contenant des valeurs manquantes
lignes_manquantes=df[df.isna().any(axis=1)]
lignes_manquantes

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
14,M0056,2026-01-07 07:00:00,C008,B003,22.33,67.42,1014.41,101.20,NaN,Normale
30,M0073,2026-01-08 00:00:00,C001,B001,23.12,63.97,NaN,186.87,OK,Normale
91,M0473,2026-01-24 16:00:00,C005,B002,21.32,70.43,1021.20,194.76,NaN,Normale
128,M0300,2026-01-17 11:00:00,C012,B004,23.32,55.73,NaN,232.38,OK,Normale
139,M0345,2026-01-19 08:00:00,C009,B003,NaN,66.77,1015.33,216.31,OK,Normale
146,M0118,2026-01-09 21:00:00,C010,B004,30.32,NaN,1015.78,261.68,OK,Elevé
149,M0034,2026-01-06 09:00:00,C010,B004,28.91,NaN,1001.23,234.30,OK,Normale
163,M0019,2026-01-05 18:00:00,C007,B003,NaN,69.97,1014.14,181.07,OK,Normale
196,M0372,2026-01-20 11:00:00,C012,B004,29.33,56.91,1020.02,NaN,OK,Normale
215,M0204,2026-01-13 11:00:00,C012,B004,NaN,59.96,1007.98,294.02,OK,Normale
270,M0334,2026-01-18 21:00:00,C010,B004,29.63,67.70,1016.30,363.68,NaN,Normale
303,M0584,2026-01-29 07:00:00,C008,B003,23.78,64.66,NaN,153.81,OK,Normale
307,M0169,2026-01-12 00:00:00,C001,B001,21.86,51.83,NaN,195.72,OK,Normale
323,M0391,2026-01-21 06:00:00,C007,B003,21.82,NaN,1006.47,98.39,OK,Normale
459,M0143,2026-01-10 22:00:00,C011,B004,28.65,66.88,1001.41,NaN,OK,Normale
476,M0527,2026-01-26 22:00:00,C011,B004,26.16,NaN,1024.21,232.87,OK,Normale
490,M0227,2026-01-14 10:00:00,C011,B004,25.13,85.60,1011.20,NaN,ALERTE,Normale
491,M0449,2026-01-23 16:00:00,C005,B002,26.82,61.99,NaN,215.34,OK,Normale
511,M0506,2026-01-26 01:00:00,C002,B001,24.04,57.10,1014.04,NaN,OK,Normale
513,M0490,2026-01-25 09:00:00,C010,B004,NaN,52.97,1010.71,253.63,OK,Normale
526,M0015,2026-01-05 14:00:00,C003,B001,23.17,79.95,1006.07,NaN,OK,Normale
536,M0252,2026-01-15 11:00:00,C012,B004,27.01,NaN,1018.36,263.13,OK,Normale
548,M0572,2026-01-28 19:00:00,C008,B003,NaN,68.63,1018.58,252.48,OK,Normale
556,M0092,2026-01-08 19:00:00,C008,B003,NaN,79.81,1007.05,113.00,OK,Normale
572,M0190,2026-01-12 21:00:00,C010,B004,24.24,73.55,1018.12,299.91,NaN,Normale

In [65]:
# 5) Température et humidité : remplacement par la moyenne
df["temperature"]=df["temperature"].fillna(df["temperature"].mean())
df["humidite_relative"]=df["humidite_relative"].fillna(df["humidite_relative"].mean())

# 6) Consommation : remplacement par la mediane
df["consommation"]=df["consommation"].fillna(df["consommation"].median())

# 7) Etat : remplacement par "INCONNU"
df["etat"]=df["etat"].fillna("INCONNU")

# Vérification
df.isna().sum()

id_mesure             0
date_heure            0
id_capteur            0
batiment              0
temperature           0
humidite_relative     0
pression              5
consommation          0
etat                  0
niveau_temperature    0
dtype: int64

# Partie 10 : Gestion des doublons

Des mesures dupliquées (ex : double envoi d'un capteur) fausseraient les statistiques et l'entraînement d'un futur modèle : elles doivent être détectées puis supprimées.

In [70]:
# 1) Nombre de doublons
print("Nombre de doublons :", df.duplicated().sum())

Nombre de doublons : 5

In [71]:
# 2) Affichage des doublons
df[df.duplicated()]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
183,M0599,2026-01-29 22:00:00,C011,B004,22.02,68.09,1005.90,227.81,OK,Normale
231,M0026,2026-01-06 01:00:00,C002,B001,22.87,77.99,1010.15,213.19,OK,Normale
355,M0147,2026-01-11 02:00:00,C003,B001,26.14,84.97,1003.59,142.31,OK,Normale
538,M0456,2026-01-23 23:00:00,C012,B004,20.68,72.69,1022.77,309.01,OK,Normale
539,M0302,2026-01-17 13:00:00,C002,B001,22.05,58.26,1007.30,140.42,OK,Normale

In [73]:
# 3) Suppression des doublons puis vérification
df=df.drop_duplicates()
print("Nombre de doublons après suppresseion :", df.duplicated().sum())
print("Nouvelles dimensions de df :", df.shape)

Nombre de doublons après suppresseion : 0
Nouvelles dimensions de df : (600, 10)

# Partie 11 : Statistiques descriptives

Un dernier tour d'horizon des données nettoyées, avant export — utile pour vérifier la cohérence globale du jeu de données.

In [74]:
# 1) Statistiques sur la température
print("Min :", df["temperature"].min())
print("Max :", df["temperature"].max())
print("Moyenne :", round(df["temperature"].mean(), 2))
print("Médiane :", df["temperature"].median())
print("Écart-type :", round(df["temperature"].std(), 2))
print("Nombre de valeurs :", df["temperature"].count())

Min : -18.5
Max : 58.7
Moyenne : 24.9
Médiane : 24.87831385642738
Écart-type : 4.05
Nombre de valeurs : 600

In [75]:
# 2) Mode et répartition des états
print("Mode de 'etat' :", df["etat"].mode()[0])
print()
print("Nombre de mesures par état : ")
df["etat"].value_counts()

Mode de 'etat' : OK

Nombre de mesures par état :

OK         562
ALERTE      29
ERREUR       5
INCONNU      4
Name: etat, dtype: int64